### ISSUE TITLE
External Dependencies

### ISSUE THREAD

**Issue by th1460** [hfshr/shiny-vue3-r#1]
Congratulation for this work. Very nice! I have a doubt. How can I include external dependencies as in `webpack`.

```
module.exports = {
  entry: './src/index.js',
  externals: {
    shiny: 'Shiny'
  }
};
```

> The above will allow importing the Shiny object in scripts, which is needed to set the input value with Shiny.setInputValue; hence Shiny must be accessible in webpack. Let us delve into the import/export mechanism. -- https://book.javascript-for-r.com/webpack-intro-discover.html 

Thanks

**Comment by hfshr** [comment]
Hey, thanks! I've found that you don't actually need to do anything extra with external deps as long as you include `{{headContent()}}` in the index.html file. Then Shiny will inject the required scripts when you run the app.  Not sure if that's the best way to go about it but seems to work! :shrug:

**Comment by th1460** [comment]
Thank you for the answer. I am using svelte in place of vue, but the `ui` work well. As I am using svelte, I think that I need make something to fix that in the `server`. Thank you again!
